"""empty message

Revision ID: 343b101b8b09
Revises: 96e9d3585e35
Create Date: 2018-07-06 02:30:01.104782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343b101b8b09'
down_revision = '96e9d3585e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'posted')
    # ### end Alembic commands ###
