"""empty message

Revision ID: 49391dbb4480
Revises: feb5f8b80ec5
Create Date: 2018-07-08 18:16:39.169131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49391dbb4480'
down_revision = 'feb5f8b80ec5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
